### PR TITLE
Development

### PR DESCRIPTION
**Pull request by MrKev312**

### CODE REVIEW

**Comment by HenkKalkwater** [comment]
At this moment, merging these branches would lead to too much work. Could you please merge with master? Right now. some changes you've made have become unnecessary. One of them is the `bool calCRC8` in `blockSendData()`, because `blockSendData()` no longer calculates the CRC8 (if you want to calculate the CRC-8 and other values of the packet, you should use `blockSendPacket()`.  The same thing goes for receiving data. Make sure to call `waitForConnection()` to initialize the connection, so that the link will automatically fill in the right `ConnectionID`). If you want to have an example, you can look at `startTransfer2()` in `link.cpp`.

Sorry for the inconvenience.

**Comment by MrKev312** [comment]
i have one question, does your wii fit meter actually connect with your 3ds because i get this result and a failed connection on the meter:
img_5167

**Comment by HenkKalkwater** [comment]
I was debugging this. I apparently there are some errors in it. I'm looking for it right now. The fit meter says `no connections available` right now, instead of `no connection found`, so I'm assuming it is.

**Comment by HenkKalkwater** [comment]
Looking at it, it's just that the 3DS still is receiving the packets with `01 04 04`. Maybe I'll need to wait until the Fit Meter stops sending those packets before sending data back to the Fit Meter.

**Comment by MrKev312** [comment]
so it should wait until it gets a 01 03 04 again?

**Comment by HenkKalkwater** [comment]
I meant it should wait until it stops receiving data with `01 04 04`..

**Pull request closed without merging**
